apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: biohazardhpkpipelinesjavascriptdocker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: biohazardhpkpipelinesjavascriptdocker 
    spec:
      containers:
        - name: biohazardhpkpipelinesjavascriptdocker 
          image: andreeak8s.azurecr.io/biohazardhpkpipelinesjavascriptdocker
          ports:
          - containerPort: 8080